version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql_sakila
    ports:
      - "30004:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: