version: '3'

services:
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-sakila
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: R00Tp4$$w0rd
