version: '3'

services:
  default:
    container_name: "defiut"
    image: defiut
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: "always"
    hostname: "defiut-docker"
